// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCK5DTc9VWS8KpVpmmijeP0GerBuKMiog',
    appId: '1:16216790793:web:dff6363b4d737ad9fe25d8',
    messagingSenderId: '16216790793',
    projectId: 'ferugson-2dacc',
    authDomain: 'ferugson-2dacc.firebaseapp.com',
    storageBucket: 'ferugson-2dacc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtdsk1H0G9xhudaQMWgLEGSIZZx7z51HI',
    appId: '1:16216790793:android:f1bd9babce0d9eb2fe25d8',
    messagingSenderId: '16216790793',
    projectId: 'ferugson-2dacc',
    storageBucket: 'ferugson-2dacc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6nDg8pf1XEYvJVkZG-bxUIeCb0UC800',
    appId: '1:16216790793:ios:f91814b4ffcf4f30fe25d8',
    messagingSenderId: '16216790793',
    projectId: 'ferugson-2dacc',
    storageBucket: 'ferugson-2dacc.firebasestorage.app',
    iosBundleId: 'com.example.ferugson',
  );
}
